/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EditTskRouteImport } from './routes/editTsk'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AddTaskRouteImport } from './routes/addTask'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EditTskRoute = EditTskRouteImport.update({
  id: '/editTsk',
  path: '/editTsk',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AddTaskRoute = AddTaskRouteImport.update({
  id: '/addTask',
  path: '/addTask',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/addTask': typeof AddTaskRoute
  '/analytics': typeof AnalyticsRoute
  '/editTsk': typeof EditTskRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesByTo {
  '/addTask': typeof AddTaskRoute
  '/analytics': typeof AnalyticsRoute
  '/editTsk': typeof EditTskRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/addTask': typeof AddTaskRoute
  '/analytics': typeof AnalyticsRoute
  '/editTsk': typeof EditTskRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tasks': typeof TasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/addTask'
    | '/analytics'
    | '/editTsk'
    | '/login'
    | '/register'
    | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to: '/addTask' | '/analytics' | '/editTsk' | '/login' | '/register' | '/tasks'
  id:
    | '__root__'
    | '/addTask'
    | '/analytics'
    | '/editTsk'
    | '/login'
    | '/register'
    | '/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AddTaskRoute: typeof AddTaskRoute
  AnalyticsRoute: typeof AnalyticsRoute
  EditTskRoute: typeof EditTskRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editTsk': {
      id: '/editTsk'
      path: '/editTsk'
      fullPath: '/editTsk'
      preLoaderRoute: typeof EditTskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addTask': {
      id: '/addTask'
      path: '/addTask'
      fullPath: '/addTask'
      preLoaderRoute: typeof AddTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AddTaskRoute: AddTaskRoute,
  AnalyticsRoute: AnalyticsRoute,
  EditTskRoute: EditTskRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
